name: Trigger auto deployment for bookingboard-service-document

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bookingboard-service-document-AutoDeployTrigger-52df2b58-9916-415c-acf7-facad7941ca4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/build
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: bookingboard.azurecr.io
          registryUsername: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_REGISTRY_PASSWORD }}
          containerAppName: bookingboard-service-document
          resourceGroup: WebServices
          imageToBuild: bookingboard.azurecr.io/bookingboard-service-document:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


