name: Continuous Delivery

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          registry: bookingboard.azurecr.io
          username: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_REGISTRY_USERNAME }}
          password: ${{ secrets.BOOKINGBOARDSERVICEDOCUMENT_REGISTRY_PASSWORD }}
      - name: Build and push Docker image for release
        run: |
          make release GOTENBERG_VERSION=${{ github.event.release.tag_name }}
          make release GOTENBERG_VERSION=${{ github.event.release.tag_name }} DOCKER_REGISTRY=thecodingmachine